# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_profile.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 568)
        Form.setStyleSheet("background-color: rgb(223, 240, 255);")
        self.returnButton = QtWidgets.QPushButton(Form)
        self.returnButton.setGeometry(QtCore.QRect(0, 0, 58, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.returnButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/openmoji_return-back-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.returnButton.setIcon(icon)
        self.returnButton.setIconSize(QtCore.QSize(24, 28))
        self.returnButton.setFlat(True)
        self.returnButton.setObjectName("returnButton")
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(40, 50, 110, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(22, 104, 277, 3))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.name_text = QtWidgets.QLabel(Form)
        self.name_text.setGeometry(QtCore.QRect(29, 135, 22, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.name_text.setFont(font)
        self.name_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_text.setObjectName("name_text")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(29, 154, 262, 26))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.name.setObjectName("name")
        self.phone = QtWidgets.QLineEdit(Form)
        self.phone.setGeometry(QtCore.QRect(30, 219, 262, 26))
        self.phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.phone.setObjectName("phone")
        self.phone_text = QtWidgets.QLabel(Form)
        self.phone_text.setGeometry(QtCore.QRect(30, 200, 22, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.phone_text.setFont(font)
        self.phone_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phone_text.setObjectName("phone_text")
        self.email = QtWidgets.QLineEdit(Form)
        self.email.setGeometry(QtCore.QRect(30, 279, 262, 26))
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email.setObjectName("email")
        self.email_text = QtWidgets.QLabel(Form)
        self.email_text.setGeometry(QtCore.QRect(30, 260, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.email_text.setFont(font)
        self.email_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email_text.setObjectName("email_text")
        self.birthday_text = QtWidgets.QLabel(Form)
        self.birthday_text.setGeometry(QtCore.QRect(30, 320, 22, 13))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.birthday_text.setFont(font)
        self.birthday_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.birthday_text.setObjectName("birthday_text")
        self.birthday = QtWidgets.QDateEdit(Form)
        self.birthday.setGeometry(QtCore.QRect(30, 340, 128, 27))
        self.birthday.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.birthday.setTime(QtCore.QTime(22, 0, 0))
        self.birthday.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.birthday.setCalendarPopup(True)
        self.birthday.setTimeSpec(QtCore.Qt.LocalTime)
        self.birthday.setDate(QtCore.QDate(2022, 1, 1))
        self.birthday.setObjectName("birthday")
        self.sex_text = QtWidgets.QLabel(Form)
        self.sex_text.setGeometry(QtCore.QRect(30, 380, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.sex_text.setFont(font)
        self.sex_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sex_text.setObjectName("sex_text")
        self.identity_text = QtWidgets.QLabel(Form)
        self.identity_text.setGeometry(QtCore.QRect(30, 431, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        self.identity_text.setFont(font)
        self.identity_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.identity_text.setObjectName("identity_text")
        self.faceRegistButton = QtWidgets.QPushButton(Form)
        self.faceRegistButton.setGeometry(QtCore.QRect(190, 500, 85, 29))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.faceRegistButton.setFont(font)
        self.faceRegistButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 95, 95);\n"
"border-radius: 14px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("akar-icons_arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.faceRegistButton.setIcon(icon1)
        self.faceRegistButton.setFlat(False)
        self.faceRegistButton.setObjectName("faceRegistButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 400, 231, 31))
        self.widget.setObjectName("widget")
        self.maleButton = QtWidgets.QRadioButton(self.widget)
        self.maleButton.setGeometry(QtCore.QRect(10, 0, 51, 24))
        self.maleButton.setChecked(True)
        self.maleButton.setObjectName("maleButton")
        self.femaleButton = QtWidgets.QRadioButton(self.widget)
        self.femaleButton.setGeometry(QtCore.QRect(70, 0, 41, 24))
        self.femaleButton.setObjectName("femaleButton")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(30, 450, 231, 31))
        self.widget_2.setObjectName("widget_2")
        self.employeeButton = QtWidgets.QRadioButton(self.widget_2)
        self.employeeButton.setGeometry(QtCore.QRect(10, 0, 61, 24))
        self.employeeButton.setObjectName("employeeButton")
        self.managerButton = QtWidgets.QRadioButton(self.widget_2)
        self.managerButton.setGeometry(QtCore.QRect(70, 0, 71, 24))
        self.managerButton.setObjectName("managerButton")
        self.success_widget = QtWidgets.QWidget(Form)
        self.success_widget.setGeometry(QtCore.QRect(60, 200, 201, 141))
        self.success_widget.setStyleSheet("background-color: rgb(255, 251, 213);\n"
"")
        self.success_widget.setObjectName("success_widget")
        self.alert_text = QtWidgets.QLabel(self.success_widget)
        self.alert_text.setGeometry(QtCore.QRect(20, 30, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.alert_text.setFont(font)
        self.alert_text.setAlignment(QtCore.Qt.AlignCenter)
        self.alert_text.setObjectName("alert_text")
        self.comfirmButton = QtWidgets.QPushButton(self.success_widget)
        self.comfirmButton.setGeometry(QtCore.QRect(60, 90, 81, 26))
        self.comfirmButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.comfirmButton.setObjectName("comfirmButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.returnButton.setText(_translate("Form", "返回"))
        self.title.setText(_translate("Form", "使用者資料"))
        self.name_text.setText(_translate("Form", "姓名"))
        self.name.setText(_translate("Form", "jjj"))
        self.phone_text.setText(_translate("Form", "手機"))
        self.email_text.setText(_translate("Form", "e-mail"))
        self.birthday_text.setText(_translate("Form", "生日"))
        self.sex_text.setText(_translate("Form", "性別"))
        self.identity_text.setText(_translate("Form", "身份"))
        self.faceRegistButton.setText(_translate("Form", "儲存"))
        self.maleButton.setText(_translate("Form", "男"))
        self.femaleButton.setText(_translate("Form", "女"))
        self.employeeButton.setText(_translate("Form", "員工"))
        self.managerButton.setText(_translate("Form", "管理者"))
        self.alert_text.setText(_translate("Form", "儲存成功"))
        self.comfirmButton.setText(_translate("Form", "確認"))

import image_rc
